# Generated by Django 6.1.1 on 2026-10-03 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('ticket_type', models.CharField(choices=[('General Pass', 'General Pass - $250,000 COP'), ('VIP Experience', 'VIP Experience - $500,000 COP'), ('Camping Pass', 'Camping Pass - $150,000 COP')], max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
